import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " flex w-[100svw]"}>
        <div className="w-[30svw] border-r-[lightgray] border-r" id="leftDiv"></div>

        <div className="w-[60svw] p-[1svw]" id="middleDiv">{children}</div>

        <div className="w-[30svw] h-[100svh]  border-l-[lightgray] border-l" id="rightDiv"></div>
        </body>
    </html>
  );
}
